#!/bin/bash
#
#   start-remote-runner
#
#   Description:
#       This script is intended to start a GitHub actions runner on a remote
#       host after being called by the cron script.
#
#   Author:         Brian Vanderwende
#   Last Revised:   20:55, 04 Dec 2024
#

# Handle arguments
runner_path="$1"
cron_log=$2

# Introspection
runner_host=$(hostname -s)
runner_pid=$$

if [[ $cron_log != tty ]]; then
    runner_log=${cron_log/_cron_/_runner_}
fi

# Runner tracking
cd $runner_path

echo $runner_pid > cron-runner.pid
echo $runner_host > cron-runner.host
echo "started" > cron-runner.status

if [[ -n $runner_log ]]; then
    echo "$(date -Iseconds) - Starting runner with pid=$runner_pid on host=$runner_host ..." >> $cron_log
    exec ./run.sh >& $runner_log
else
    echo "$(date -Iseconds) - Starting runner with pid=$runner_pid on host=$runner_host ..."
    exec ./run.sh
fi
