#!/bin/bash
#
#   stop-remote-runner
#
#   Description:
#       This script is intended to stop a GitHub actions runner on a remote
#       host after being called by the cron script.
#
#   Author:         Brian Vanderwende
#   Last Revised:   23:42, 20 Nov 2024
#

my_user=$(whoami)

# Handle arguments
runner_pid=$1

# We need to stop Runner.Listener for a clean exit
while [[ $cmd_name != Runner.Listener ]]; do
    read cmd_pid cmd_name <<< $(pgrep -u $my_user -l -P ${cmd_pid:-$runner_pid})
done

if [[ -n $cmd_pid ]]; then
    kill -s INT $cmd_pid

    while kill -0 $runner_pid 2> /dev/null; do
        sleep 1
    done
else
    exit 1
fi
